### PR TITLE
Try out the new Travis container-based infrastructure

### PR DESCRIPTION
**Pull request by kirbyfan64**
This will likely fail at first, but Travis won't run unless this is a PR, so...yeah...

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Hmm...looks like Figlet isn't an approved package. Opened travis-ci/apt-package-whitelist#2756 for that. Meanwhile, would you if I put a dummy "figlet" that just re-prints the input text when run on Travis?

**Comment by tonyfischetti** [comment]
Sure, where would you put the dummy figlet?

**Comment by kirbyfan64** [comment]
I guess I could have `.travis.yml` just run `echo 'echo "$@" > figlet'` and add the current directory to the path.

**Comment by tonyfischetti** [comment]
Hey, what's the status for this?

**Comment by kirbyfan64** [comment]
Holy crap, I completely forgot about this. So sorry!

**Comment by kirbyfan64** [comment]
I'm re-running Travis; since Figlet was added to the apt whitelist already (because this took so long!), it should work now. Hopefully.

**Comment by kirbyfan64** [comment]
@tonyfischetti It passed now!

**Comment by tonyfischetti** [comment]
Great! Thanks!

**Pull request merged**
