### PR TITLE
Various

### PR DESCRIPTION
**Pull request by kirbyfan64**
Does lots of stuff. The tests aren't a lot. In fact, they're barely anything. Hehehe....

### CODE REVIEW

**Comment by tonyfischetti** [comment]
How come the last commit failed?

**Comment by tonyfischetti** [comment]
It's still failing :(

**Comment by kirbyfan64** [comment]
I think I got it all this time. Sorry it took so long.

I also added more tests and added docstrings, as well as renamed expand_macros to expand_macros_and_includes, since the former name is very misleading. :)

**Comment by tonyfischetti** [comment]
Awesome! Thanks!

**Pull request merged**
