### PR TITLE
Fix #50 (and some other stuff)

### LINKED ISSUE #50: Sake gets confused by patterns
What I expect the Sakefile below to do is
 1. Run target "download 193L"
 2. Run target "count residues in 193L.fasta"

Here is what happens instead:
```sh
$ sake -r
Would run target: count residues in %pdb.fasta
Would run target: download 193L
```

```sh
$ sake
Running target count residues in %pdb.fasta
grep -v '^>' %pdb.fasta | fold -w1 | sed -e s/A/ala/ -e s/R/arg/ -e s/N/asn/ -e s/D/asp/ -e s/C/cys/ -e s/Q/gln/ -e s/E/glu/ -e s/G/gly/ -e s/H/his/ -e s/I/ile/ -e s/L/leu/ -e s/K/lys/ -e s/M/met/ -e s/F/phe/ -e s/P/pro/ -e s/S/ser/ -e s/T/thr/ -e s/W/trp/ -e s/Y/tyr/ -e s/V/val/ | tr '[:lower:]' '[:upper:]' | sort | uniq -c > %pdb.fasta-counts;
grep: %pdb.fasta: No such file or directory
File '%pdb.fasta' could not be read! Exiting!
```

Sake takes the pattern %pdb as a file name and runs the patterned target first. It works fine if I run "dowload 193L" manually before a plain `sake`.

```yaml
#! DOWNLOAD_PDB = wget http://www.rcsb.org/pdb/files/
#! DOWNLOAD_FASTA = wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=

download 193L:
  help: download protein structure 193L from the PDB 
  dependencies:
  output:
    - 193L.fasta
  formula: >
    ${DOWNLOAD_FASTA}193L -O 193L.fasta;

count residues in %pdb.fasta:
  help: count the residues in the FASTA sequence file
  dependencies:
    - "%pdb.fasta"
  output:
    - "%pdb.fasta-counts"
  formula: >
    grep -v '^>' %pdb.fasta | fold -w1 | sed -e s/A/ala/ -e s/R/arg/ -e s/N/asn/ -e s/D/asp/ -e s/C/cys/ -e s/Q/gln/ -e s/E/glu/ -e s/G/gly/ -e s/H/his/ -e s/I/ile/ -e s/L/leu/ -e s/K/lys/ -e s/M/met/ -e s/F/phe/ -e s/P/pro/ -e s/S/ser/ -e s/T/thr/ -e s/W/trp/ -e s/Y/tyr/ -e s/V/val/ | tr '[:lower:]' '[:upper:]' | sort | uniq -c > %pdb.fasta-counts;
```

### PR DESCRIPTION
**Pull request by kirbyfan64**
This fixes #50 and renames expand_macros_and_includes to preprocess, since that is MUCH more obvious.

### CODE REVIEW

**Comment by tonyfischetti** [comment]
I can't merge a pull request that breaks our CI. Why did the CI build fail?

**Comment by kirbyfan64** [comment]
@tonyfischetti I think I fixed it. Unfortunately, I can't run all the functests on my laptop because stupid Cabal killed Pandoc for some wretched reason...fingers crossed!

**Comment by kirbyfan64** [comment]
@tonyfischetti It works now!

**Comment by kirbyfan64** [comment]
@tonyfischetti I also added a fix for #54.

**Comment by kirbyfan64** [comment]
@tonyfischetti ...and I fixed a bug with handling the `all` target that I didn't notice till now. That was a close one...

**Comment by tonyfischetti** [comment]
Neat! Thank you so much for fixing these :)

**Pull request merged**
