### PR TITLE
Implement empty macros, -D, ?=, and or

### LINKED ISSUE #52: Allow defines to be passed on the command line (and add ?=)
This would fix #49 easily:

```yaml
# define FILE if not already defined
#! FILE ?= 193L
# or
#! FILE or You need to define file first!
# format: <macro> or <error message if not defined>
#! DOWNLOAD_PDB = wget http://www.rcsb.org/pdb/files/
#! DOWNLOAD_FASTA = wget http://www.rcsb.org/pdb/download/downloadFile.do\?fileFormat\=fasta\&structureId\=

"download $FILE":
  help: download protein structure 193L from the PDB 
  dependencies:
  output:
    - "$FILE.pdb"
    - "$FILE.fasta"
  formula: |
    ${DOWNLOAD_PDB}$FILE.pdb
    ${DOWNLOAD_FASTA}$FILE -O $FILE.fasta
```

One would invoke Sake like so:

```
$ sake -DFILE=value
```

As always, I'd be happy to open a PR, and this time I'll try to make it less bug-laden. ;)

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #52 and #65.

### CODE REVIEW

**Comment by tonyfischetti** [comment]
Awesome, it looks like the failing Travis tests are because of something trivial. I'll be checking this tonight :)

**Comment by kirbyfan64** [comment]
Build's green now!

**Comment by tonyfischetti** [comment]
You are gentleman and a scholar

**Comment by tonyfischetti** [comment]
I'll close the relevant issues once I stress test these new additions tonight or tomorrow afternoon

**Pull request merged**
